### ISSUE TITLE
0.18 % of all data carrying default values

### ISSUE THREAD

**Issue by michaelaye** [zooniverse/MarsZoo#105]
I have identified 5764 fan classifications (0.172 %) and 7365 blotch classifications (0.177 %) that carry the signature of default values **at coordinates (0,0)!**, that in my opinion are hard to create on purpose due to the inherent difference between mouse cursor position and exact position where a marking is positioned at mouse-click (i.e. they are several pixel apart)
I found the below linked stacks of classifications by doing a search for
* blotches that have (x, y, radius_1, radius_2, angle) == (0, 0, 10, 10, 0 )
* fans that have (x, y, distance, angle, spread) = (0, 0, 10, 0, 1)

Here is a plot over time, showing how many of these have been found with the same classification_id. This is also the meaning of the number in below linked files: It's how many entries for this classification_id carry these default data values.
![Default data over time](https://www.dropbox.com/s/cn1quxfg2blrzzw/default_value_data_times.png?dl=1)

Sometimes the same user creates these kind of classifications with a different classification_id for the same image_id, maybe related or just a problem on top of the #100 issue.

Here are the files with the metadata for these kind of classifications:

https://www.dropbox.com/s/zo046s9vsv7e918/default_data_fans.csv
https://www.dropbox.com/s/ukd1xwo1ujzz4hg/default_data_blotches.csv

**Comment by mschwamb** [comment]
As per the December telecon, I think since the December telecon. we've sorted this as a script drop and able to remove them. I've written up what i discussed on the telecon in the current paper draft. Can we close this ticket for bookkeeping? 

Thanks.
