### ISSUE TITLE
Hungarian translation needs some updates

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/MarsZoo#110]
Hi @chrissnyder 
Sorry for sending an email. I should have stuck it here from the beginning. So I'm posting it here. 

I noticed the Hungarian (Magyar) translation of Planet Four still has the old tagline. Also the 'see examples' on the interface is still in English for it.  I wanted to let you know in case the json needed to be uploaded.

Cheers,

~Meg

**Comment by chrissnyder** [comment]
I'm going to close this just for tidiness sake, but very aware text changes breaks translations.
