### ISSUE TITLE
Something wrong - Fan spread angle bug not completely corrected or not being updated in csv file 

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/MarsZoo#128]
@brian-c and @chrissnyder can you help check this please?

This refers back to issue #107 

We plotted up some of the gold standard data 

image id : APF0000kou

![71_apf0000kou_fans](https://cloud.githubusercontent.com/assets/753325/5770784/91864978-9d6b-11e4-97e8-2e8808055b18.png)
where everybody drew in version 1 flag, you can see that the fans spreads are still too small. the top left panel is the volunteer markings. top right is markings from  michael from the science team, lower right is markings from anya from the science team and lower left is markings from meg from the science team  
Especially for the science team they should have nailed it. 

michael's (michaelaye) fan -
distance = 282.2144470214844 angle=-154.16131591796875 
corrected spread (in csv)= 21.50283432006836 
classification_id = 537a52ec241fe143c400092a

anya's (Portyankina) fan:
distance = 330.71136474609375 angle = -155.52737426757812
 corrected spread (in csv) =16.88918113708496
classification_id=537bd0f7241fe13f2a000be0
in this one I drew with version 2 of the flag and my fans match the shape but the volunteers don't. they drew with version 1.0 

 image id APF0000prj
![22_apf0000prj_fans](https://cloud.githubusercontent.com/assets/753325/5770805/1f74426c-9d6c-11e4-9d9e-93b4b33e2d6e.png)

the csv file was supposed to be outputted with a  corrected for the spread angle for those impacted. we thought we checked that and it was giving correct results.  has that changed? is the correction you came up with correct. can you help check this with us. do you get a different spread that what we have in the csv file for these sources

in case you need it - the science team zooniverse usernames are michaelaye, mschwamb, Portyankina
We're trying to submit the paper in the next few months and so we need to understand what's going on. 

Can you help?

Thanks, 

~Meg

**Comment by michaelaye** [comment]
Wow, thanks for fishing out all the details, Meg. I checked all the other fan marking overviews that I created today, and in every other image it looks like the fan angle fits very well. It's just the one from above (APF... kou) which is weird. I really can't imagine that both Anya *AND* me mess it up the same way??

**Comment by mschwamb** [comment]
Yeah the fan spread is now outputting the correct values in the interface. It seems it's something to do with the spread correction for your markings. For APF0000kou you and Anya drew with the old interface before the spread patch was in. I'm assuming it's either that the correction formula for the spread angle isn't being applied in the csv file anymore or  the correction formula is off somehow. @brian-c  and @chrissnyder can hopefully help.

**Comment by chrissnyder** [comment]
Was the fan spread values ever fixed in the CSV file? I see where we added the version column, but not seeing where we corrected old input.

**Comment by mschwamb** [comment]
In the end of the previous ticket in this. I ask this and Michael Parrish says to that it should be or at least that's my interpretation of the response. Can you add in the correction that Brian has written in #107?

**Comment by mschwamb** [comment]
@parrish while you're fixing the csv file, can you also incorporate this as well? 
Thanks, 

~Meg

**Comment by parrish** [comment]
Ah, I thought that only the version column needed to be added.  So just to clarify, all version 1 classifications need to have the spread correction applied from #107?

**Comment by mschwamb** [comment]
Yes, all version 1 fans need to have the spread correction applied.

**Comment by mschwamb** [comment]
Also can @parrish can you generate an email with the csv link once you're able to fix the generating bug and added in the spread correction for version=1 fans. That would be really helpful.

Thanks, 

~Meg

**Comment by mschwamb** [comment]
@parrish and @chrissnyder is it possible to get a csv file with the corrected spread values by sometime early next week. We have a team telecon at the end of it, and it would be good to be able to discuss using the new spreads and classification counts.

Thanks, 

~Meg

**Comment by parrish** [comment]
This is on my to-do list for today.  It'll take a while to reprocess data, but it should hopefully finish before the data processing run on Sunday.  If not, I'll generate something when it does.

**Comment by mschwamb** [comment]
Thanks @parrish

**Comment by parrish** [comment]
The data export should be fixed if you want to check it out.  If it looks correct, I'll update the classifications themselves for completeness too.

**Comment by mschwamb** [comment]
We're looking at it this week. I'll update the ticket once we've checked the plots again.  We did get the csv file yesterday. What do you mean by updating the classifications themselves? I believe @chrissnyder want to keep the database entries as in in the MongoDB so it is the original record of what was stored.

**Comment by mschwamb** [comment]
A note to say that the correction applied now reproduces the correct spread angle. I'm posting images of the annotations to show the difference 
![54_apf0000prj_fans 1](https://cloud.githubusercontent.com/assets/753325/5985009/2408fc12-a917-11e4-9aa2-97141c07d4f2.png)

![47_apf0000kou_fans](https://cloud.githubusercontent.com/assets/753325/5985010/261a7486-a917-11e4-98d6-1478a515ed52.png)

I think for now we just leave this updating in the csv file, unless @chrissnyder agrees to have the database updated and the original bad spread angles stored.


Thanks, 

~Meg
