### ISSUE TITLE
Going back to finish 4000 cutouts from Season 2 and Season 3 needed for the first paper

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/MarsZoo#130]
I checked the status of the cutouts from Season 2 and Season 3 and there are 4000 (10% of the total cutouts from those seasons) that don't have at least 30 classifications. We decided in the telecon last week that we want to try and get them closer to 30 and complete if possible.

Can you please switch on and off some cutouts so that we can push classifications to the season 2 and season 3 data. Details below:

- [x] Can you please first get a list of which APF ids are currently active so it will easier to turn back on Inca City images later
- [x] Pause all cutouts and make sure the ones on this list https://dl.dropboxusercontent.com/u/56971802/P4_season23_active_cutouts.csv become/stay active

We're also going to have a newsletter to make a push with the volunteers. Newsletter will go out once this is done. 

Thanks

**Comment by chrissnyder** [comment]
Done.

For the record, I'm not really a fan of swapping datasets in and out manually like this. Happy to do so when needed, but would like to only do so when absolutely necessary.

**Comment by michaelaye** [comment]
we only have to do it whenever the system prematurely retires images. ;) if we have less stats for some images than for others their relevance gets voted down and we would like to avoid that.

**Comment by mschwamb** [comment]
Just to clarify - The system didn't premature retire them, it just it was a small amount so it never got finished when we got close to be doing and shutting down data. No 100% sure why I missed that fact earlier. That was my not fault for not catching this earlier. 

@chrissnyder agreed about swapping datasets and duly noted for the next time.  These images have been sitting for almost  a year not completing so if we want the paper in the timeline we need to do this. One note though perhaps for the new system being built. If we had the flexibility to add different priority to any list of cutouts, then we would have just increased the frequency for these show and  left in the new data as active. My understanding is that's not trivial unless set up from the beginnning when the data is uploaded.

**Comment by michaelaye** [comment]
I see, so a premature switch was made to avoid any citizen suddenly have no data to see? Would that really happen?

**Comment by mschwamb** [comment]
Shouldn't have and double checking this morning again, I found  a bug in my mysql query. I was including apparently season 4 data  that we're classifying now  as season 2 and season 3 so that's how I get 4000.  Small upside 400  season 2 and season 3 cutouts (which make more sense) are currently active and as of yesterday they're all now at basically 29 and 30. A complete screw up on my part. @chrissnyder you've got mail with more details and an apology.
