### ISSUE TITLE
Next HiRISE images for upload 

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/MarsZoo#133]
Hi,

We're going to be done with Inca City Season 4 soon. We'd like to focus on getting to four years of classifications for another region on Mars dubbed Manhattan. We would need the following HiRISE images processed into cutouts and uploaded into the database:

ESP_030184_0940
ESP_029762_0940
ESP_029406_0940
ESP_029050_0940
ESP_029024_0940
ESP_029143_0935
ESP_028998_0935
ESP_028932_0935
ESP_028931_0935
ESP_029934_0935
ESP_029657_0935
ESP_029578_0935
ESP_029301_0935
ESP_029090_0935
ESP_029037_0935

Any chance we could get this data processed and live before the cratering test goes live?

Thanks

**Comment by chrissnyder** [comment]
https://drive.google.com/a/zooniverse.org/file/d/0Bwb8Rkj3mY9ZNFdXZVRKVnhaUzQ/view?usp=sharing

How's this look? Given a thumbs up, I can have the data active shortly after.

**Comment by mschwamb** [comment]
Looks good to upload. Thanks very much.  But let's leave this paused for the time being. We'll need it very soon, but the. team wants to make sure Inca City gets completed, since it can be its own paper and gives us multiple reasons for newsletters that are needed for the next few weeks.  There are supposed to be a few. First one can be finishing up Inca City, and second can be releasing the new Manhattan data. We will need to switch to Manhattan very soon (as early as next week if the response to the second newsletter is huge).

**Comment by chrissnyder** [comment]
Roger that, just give me a poke when ready to swap/add new data.

**Comment by mschwamb** [comment]
Hey @chrissnyder ,

We're at 99% complete with what's currently live. Can you push these images live?

Thanks, 

~Meg

**Comment by michaelaye** [comment]
Here is the complete list of Manhattan image numbers. Note that for season
4 we have two different Manhattan seasons defined, distinguishable by their
coordinates.

class Manhattan:
    lat = --85.751
    lon = 105.971
    season4 = ['ESP_030184_0940',
               'ESP_029762_0940',
               'ESP_029406_0940',
               'ESP_029050_0940',
               'ESP_029024_0940']


class Manhattan2:
    lat = -86.39
    lon = 99
    season4 = ['ESP_028932_0935',
               'ESP_028931_0935',
               'ESP_029934_0935',
               'ESP_029657_0935',
               'ESP_029578_0935',
               'ESP_029301_0935',
               'ESP_029090_0935',
               'ESP_029037_0935']
    season3 = ['ESP_022339_0935',
               'ESP_021468_0935',
               'ESP_020888_0935',
               'ESP_020532_0935',
               'ESP_020255_0935',
               'ESP_022260_0935',
               'ESP_021495_0935',
               'ESP_021455_0935',
               'ESP_020954_0935',
               'ESP_020598_0935',
               'ESP_020519_0935',
               'ESP_020321_0935',
               'ESP_020214_0935',
               'ESP_020202_0935']
    season2 = ['ESP_011394_0935',
               'ESP_011671_0935',
               'ESP_011961_0935',
               'ESP_012251_0935',
               'ESP_012739_0935',
               'ESP_012821_0865',
               'ESP_012884_0935',
               'ESP_013016_0935',
               'ESP_013095_0935']
    season1 = ['PSP_003285_0935',
               'PSP_003430_0935',
               'PSP_003746_0935',
               'PSP_003773_0935',
               'PSP_003997_0935',
               'PSP_004142_0935',
               'PSP_004920_0935',
               'PSP_002532_0935',
               'PSP_002533_0935',
               'PSP_002850_0935',
               'PSP_002876_0935',
               'PSP_002942_0935',
               'PSP_003496_0935',
               'PSP_003523_0935',
               'PSP_003575_0935',
               'PSP_003641_0935',
               'PSP_005579_0935']

**Comment by chrissnyder** [comment]
Data online.

**Comment by michaelaye** [comment]
Thanks!
