### ISSUE TITLE
Today's CSV dump fails to download

### ISSUE THREAD

**Issue by michaelaye** [zooniverse/MarsZoo#134]
Error message:

```xml
<Error>
<Code>NoSuchKey</Code>
<Message>The specified key does not exist.</Message>
<Key>
ouroboros/2015-03-29_planet_four_classifications.csv.tar.gz
</Key>
[redacted]</Error>
```
 
[link removed]

**Comment by mschwamb** [comment]
Just a reminder that this is public so anyone can see the issue tickets and hyperlinks and access them. Probably best to make sure the zooniverse download link is not listed in this ticket and send it in email.

Cheers, 
~Meg

**Comment by michaelaye** [comment]
Gna... this is highly annoying. Links removed.

**Comment by mschwamb** [comment]
No csv email was sent at all this Sunday. Is it possible to manually run the code and send us a copy?

Thanks, 
~Meg

**Comment by michaelaye** [comment]
I received an email at 8:26 AM, but the link was broken again. When I clicked it I got this displayed in the browser (secret link removed):
```bash
NoSuchKeyThe specified key does not exist.ouroboros/2015-04-05_planet_four_classifications.csv.tar.gz[...deleted...]
```

**Comment by mschwamb** [comment]
@chrissnyder is there any chance someone might be able to look at this so we can get a working copy on sunday?

**Comment by mschwamb** [comment]
@astopy happened again with today's email (sent a few hours ago) with the link to the csv file if that's helpful.

**Comment by michaelaye** [comment]
yep, here as well. that's 3 weeks no working CSV dump. :(

**Comment by astopy** [comment]
Sorry about this. I’ll hopefully have this working again this week.

**Comment by parrish** [comment]
Hey, I just found out about this.  It looks like the latest batch of data had a slightly different format for the metadata that caused the export to fail.  I'm correcting it now.

I'm leaving this issue open until we confirm that it's fixed.

**Comment by michaelaye** [comment]
Does this mean that we have to wait until next Sunday to see if it worked? Could we maybe get an early dump triggered, I really would like to check the progress in our last 3 weeks because it triggered a new data upload and I want to double-check if we have currently all data active that needs to be. Cheers.

**Comment by parrish** [comment]
Just regenerated it, and emailed a link

**Comment by michaelaye** [comment]
Thanks! Much appreciated.
