### ISSUE TITLE
At 99% complete - subjects to unpause when we hit 100%

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/MarsZoo#137]
We're going to head back to the region we were looking at in the late fall.Ithaca season 1. Those images are already loaded. We'd like have the status of the APF ids of those HiRISE image id where in the meta data (name should be the variable) is-

PSP_002622_0945
PSP_002675_0945
PSP_003176_0945
PSP_003193_0850
PSP_003308_0945
PSP_003309_0945
PSP_003310_0855
PSP_003453_0945
PSP_003466_0945
PSP_003677_0945
PSP_003730_0945
PSP_003756_0945
PSP_003796_0950
PSP_003822_0945
PSP_003954_0945
PSP_004033_0945
PSP_004178_0945
PSP_004666_0945
PSP_004891_0945

If it's not possible to wait until we're out of data, then please do push these live when it's convenient.

**Comment by mschwamb** [comment]
We're 100% complete with the subjects that were live. @chrissnyder could you make these live/unpause them tomorrow? 

Thanks.

**Comment by chrissnyder** [comment]
Going live now.

**Comment by mschwamb** [comment]
Thanks @chrissnyder
