### ISSUE TITLE
Getting a redirect when we're ready for P4 terrains

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/MarsZoo#138]
We'd like to have redirect for the panoptes project to make an easier url for people to remember and also keep the project under the planet four umbrella. If possible we'd like to have http://terrains.planetfour.org  redirect to the panoptes project when we're ready to launch it.

Is this doable?

Thanks.

**Comment by mschwamb** [comment]
@chrissnyder is it doable to get a redirect to what the production address for P4: Terrains will be? It looks like launch of the new system is very very soon

This is only if you have time. I understand you're super busy with other high priority items and that this is low in the queue

**Comment by mschwamb** [comment]
@chrissnyder when things calm down or if you have a free second to breathe, would this be doable sometime soon. We can live without it for launch, but I think in the long term this would be helpful

**Comment by chrissnyder** [comment]
If things all seems good after we flip the switch, I'll have the link added shortly thereafter.

**Comment by mschwamb** [comment]
Thanks. Wishing you smooth sailing

**Comment by chrissnyder** [comment]
Done (will take a couple minutes).
