### ISSUE TITLE
Pulling the Cratering link on the front page on June 1st

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/MarsZoo#139]
The current plan with @mrniaboc  is for a newsletter to go out early next week and then pull the cratering link off the front page a week later on Monday June 1st.

**Comment by chrissnyder** [comment]
Will do. Ping me if I forget.

**Comment by mschwamb** [comment]
Will do. @mrniaboc should be sending the newsletter out today for the final push for craters.

**Comment by mschwamb** [comment]
@chrissnyder I think at your convenience, you can pull the craters link and restore it to the previous version with the social media links while we're waiting for Terrains to launch. @mrniaboc, please shout if that's not okay.
