### ISSUE TITLE
P4: Terrains spotters' guide

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/MarsZoo#140]
I didn't want to put this on pantopes-front end. The original plan with @chrislintott  was  that we would  be able to  get a custom spotters' guide for P4;Terrains.  We have everything put together 

Format can be found [here](https://www.dropbox.com/s/3fp09gv25foavr5/Spotter_guide_draft.pdf?dl=0) 

Supporting images can be found [here](https://www.dropbox.com/sh/lhaa21vd5flapi9/AABE1JKck3HyW9oLceRf5pEua?dl=0)  

@chrislintott  and @mrniaboc - can someone help us put this together?

**Comment by mrniaboc** [comment]
@simoneduca is working on implementing this for you.

**Comment by simoneduca** [comment]
Hi @mschwamb would you like the Spotter's guide link at the bottom of the pop up?
![screen shot 2015-06-15 at 17 36 06](https://cloud.githubusercontent.com/assets/8989606/8165039/1335806c-1385-11e5-97f8-219b3df4ace0.png)

**Comment by mschwamb** [comment]
@simoneduca yes if it can be linked in. 

 Basically whatever you're willing to make us in this condensed time frame.. I'm assuming the simplest that still fits into a 'panoptes self-made project' is a separate page that we add in as a external url for the top navigation bar and then link in on the help. 

Also any feedback or comments on the sketch outline of the Spotters' guide is very welcome.

**Comment by simoneduca** [comment]
@mschwamb Sure no problem. I'm almost done. Just one thing, image sg_APFT00000074 is missing from the dropbox folder you shared.

**Comment by mschwamb** [comment]
hmm let me go add that

**Comment by simoneduca** [comment]
Got it thanks.

**Comment by mschwamb** [comment]
Sorry about that and thanks!

**Comment by mschwamb** [comment]
Hi @simoneduca, just wanted to give the heads up we're trying to launch this project with panoptes so if its possible to see the spotters guide in the new day or two in case we need to make any changes before launch that would be great. Thanks for all the help. It's very much appreciated. 

~Meg

**Comment by simoneduca** [comment]
Hi @mschwamb, page is ready to view here  http://terrains-guide.planetfour.org/.
Let me know if you have any questions.

**Comment by mschwamb** [comment]
@simoneduca  - Awesome thanks. We might have one or two small changes based on looking at if that's okay. I can put issues on its github repo.  Thanks for making this. First look is that it is absolutely gorgeous!

**Comment by simoneduca** [comment]
@mschwamb no problem, happy to help. Please put your isssues here https://github.com/zooniverse/planetfour-terrains-guide/issues
