### ISSUE TITLE
Missing data dump

### ISSUE THREAD

**Issue by michaelaye** [zooniverse/MarsZoo#144]
Hi!
can it be that with all the database stress for the new site somebody accidentally deleted the regular CSV dump for PlanetFour? Because I didn't get an email about it yesterday as I usually do on Sundays.

**Comment by mschwamb** [comment]
This might be a question for @astopy and @parrish

**Comment by parrish** [comment]
We've had some issues with our data export machine running out memory trying to compress files.  @astopy It looks like this is still failing.

**Comment by astopy** [comment]
@parrish Looks like you've run this successfully... is that permanently fixed or do we still need to do something to get it working long-term?

**Comment by parrish** [comment]
Permanently-ish.  The data processing instance is still using our old deployment setup.  Also, adding gem dependencies (pg) that required native libraries to be installed required the instance to be rebuilt.

**Comment by michaelaye** [comment]
Hi, could we have another dump please? Cheers.

**Comment by astopy** [comment]
This should be fixed now.

**Comment by michaelaye** [comment]
Just to tune my expectation, will the dump arrive on Tuesdays now like yesterday?

**Comment by astopy** [comment]
It should usually still arrive on Sunday/early Monday, but the next one might be a little later if it doesn't run on schedule like it's supposed to. (I'll be checking it to make sure it runs, and I'll start it manually if not.)

**Comment by michaelaye** [comment]
Last dump has not been sent out again?

**Comment by astopy** [comment]
Oops, I made a typo in the schedule and accidentally set it to run every five years instead of every week (as it turns out, an easier mistake than you’d think). It should be working now.

**Comment by michaelaye** [comment]
You got me intrigued! I'm doing a lot of time based calculations and can not come up with a time coordinate system where a typo could be making 5 years equivalent to 1 week=7 days ... Unless you have to do things in hours and you added a digit after 7*24=168 ? 1680 would be 4.6 years, so, close to the 5 years you stated?

**Comment by astopy** [comment]
Hah, well the scheduling system has a way to randomise the precise times that tasks run to avoid everything running at once. The schedule is written similar to the Unix cron system, if you’re familiar with that, where there are columns for minutes, hours, day, month, and day of week. A “H” in a column means that it generates a random value (or “hash”), and a “*” in a column means it ignores that column. I wanted to set it to run every Sunday, so the schedule should have been “H H * * 0” for a random minute/hour on every Sunday, but I accidentally typed “H H H H 0” which means it generated a specific day and month too (in this case it generated November 6 if I remember correctly), so it would only run on November 6 and only when it happened to fall on a Sunday.

With that config it would have last run in 2011 and next in 2016, though now that I check the next year after that would have been 2022 so it would have been even longer than five years.

**Comment by michaelaye** [comment]
Ah the cron jobs, yes they are special. ;) thanks for sharing!
