### ISSUE TITLE
Adding new data if we need it due to spike in activity

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/MarsZoo#145]
We should have the PR going out today, but the decision could change from the people in charge of making those decisions- in case get through Ithaca season one, we'd like to unpause another season 1 region

can we turn on when needed subjects associated with the following HiRISE image ids

PSP_004002_0845
PSP_003246_0950
PSP_003734_0950
PSP_003786_0950
PSP_003787_0950
PSP_003866_0950
PSP_003932_0950
PSP_004024_0950
PSP_004736_0950
PSP_005119_0950
PSP_004028_0850
PSP_003474_0850
PSP_004041_0850

If we can get Ithaca done first that would be better, but whatever is best for the development team  I can reply to the ticket when we're getting closer to completion or if you think we should just make this live so it's ready, then that's fine too.

**Comment by michaelaye** [comment]
If this is meant to be Giza season1, then also these 4: (see this file for our main regions image IDs: https://github.com/CitizenScienceInAstronomyWorkshop/P4_sandbox/blob/master/planet4/region_data.py

               'PSP_002600_0955',
               'PSP_004380_0950',
               'PSP_003958_0950',
               'PSP_004028_0850',

**Comment by mschwamb** [comment]
@michaelaye the last one of those is in my list. The other three aren't listed in the excel spreadsheet Anya originally sent around for Season 1 so those aren't uploaded. I don't know why those were omitted from the list. So the list I have above is complete for what we have stored on AWS for season 1. Probably worth finding out why those images weren't on the list

**Comment by michaelaye** [comment]
I have extracted my list from the Excel spreadsheet that Candy sent around months ago.

**Comment by mschwamb** [comment]
Except that one is apparently different than the one Anya sent. I'm looking at the one from Anya that was sent to Arfon and the list for data upload of Season 1. I can forward it to you

**Comment by mschwamb** [comment]
Anyway we've sorted in email - we're happy with the original list I have in the ticket to make active. We're waiting for word the PR is actually going out

**Comment by mschwamb** [comment]
@chrissnyder we'd like to push this set live (change from paused to active) sometime next week if that would be possible. We're trying to make a push this week on the blog, etc to try and make room for new data.  Early next week would be good since then we can incorporate it with the last newsletter for the sticker stuff, but whatever timeline works best for the development team is fine by us.

**Comment by chrissnyder** [comment]
Done.
