### ISSUE TITLE
Terains redirect not working in safari?

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/MarsZoo#146]
Got an email I forwared to @chrissnyder and the P4 list about the redirect for Terrains not working in Safari due to a long outstanding issue. @michaelaye caught this so I don't really know the details. Is there anything that can be done to sort that for Safari users? Note it seems to be working for me in Safari 8.07

**Comment by michaelaye** [comment]
Are u sure? I am using 8.07 and I only get this:

<img width="1225" alt="screenshot 2015-07-24 13 06 05" src="https://cloud.githubusercontent.com/assets/69774/8882538/d916085e-3204-11e5-9412-a0ead6a6ebe2.png">

**Comment by mschwamb** [comment]
I'm on version Version 8.0.7 (10600.7.12) and it's coming just fine for me 6 minutes ago and now  on my mac and it's coming just fine for me in Taiwan - maybe @chrissnyder can replicate it ?

**Comment by mschwamb** [comment]
Missed this on panoptes front end https://github.com/zooniverse/Panoptes-Front-End/issues/1215 so closing it here in favor of the one over there
