### ISSUE TITLE
Create a second redirect for Planet Four: Terrains to match the second Planet Four redirect

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/MarsZoo#147]
@chrislintott suggested that we should have a second redirect for Planet Four: Terrains to mimic the http://www.planet4.org  redirect we have for main P4. When there's a free moment can someone make http://terrains.planet4.org redirect to the Terrains website.

**Comment by chrissnyder** [comment]
Done. Might take a couple minutes to show up though.

**Comment by mschwamb** [comment]
Thanks!
