### ISSUE TITLE
getting list of APF ids of subjects mentioned in collections and on anywhere on Talk with  boulder associated hashtags

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/MarsZoo#148]
This request might be for @parrish  - For a summer student project, I'd like my student to see if she can find boulders in other areas than the one known area based on what people have identified on Talk - would it possible to get the APFids associated with the following from Talk 

Talk Collections:

CPFL00001l
CPFS0001c6

and subjects and contents of collections marked with the following hashtags in Talk:

#boulder
#boulders
#bubble
#Snowballs 

Many Thanks.

**Comment by parrish** [comment]
Sent!
