### ISSUE TITLE
Removing the # from the url redirects for terrains

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/MarsZoo#150]
Since they just removed the hash from the panoptes address, @chrissnyder can you please remove the # from both redirects for http://terrains.planetfour.org and http://terrains.planet4.org when you have time. It redirects again to remove the hash so people can get to the site, but since some Safari browsers have issues with the hash, probably best to remove it since we can. Thanks.

**Comment by chrissnyder** [comment]
Done.
