### ISSUE TITLE
New Data to unpause for P4 classification challenge

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/MarsZoo#153]
@astopy for the challenge we want to hit 5 million classifications. Can we start with unpausing those subjects that have associated name entry with these HiRISE filenames:

PSP_002399_1025
PSP_002544_1025
PSP_002900_1025
PSP_003322_1025
PSP_002758_0945
PSP_002759_0855
PSP_003179_0945
PSP_003180_0945
PSP_003181_0855
PSP_003363_0945
PSP_003364_0945
PSP_003614_0945
PSP_003680_0945
PSP_003970_0945
PSP_004062_0945
PSP_004181_0945
PSP_004748_0945
PSP_004880_0945
PSP_002567_0955
PSP_002936_0955
PSP_003068_0955
PSP_003213_0955
PSP_003424_0955
PSP_003824_0845
PSP_003912_0955
PSP_004202_0955
PSP_004941_0955
PSP_005046_0955
PSP_003345_0955
PSP_003982_0845

On top of what we currently have live this would need 325240 to be finished off and we only 176019 classification to hit 5 million, so I think it provides good buffer. @mrniaboc wanted to announce the competition on Monday Dec 14 if this still works for to be able to turn them on over the coming days.

**Comment by mschwamb** [comment]
I'm not sure if you're familiar with the P4 database structure and what I mean by name, but if it helps APF0000yy3 is associated with PSP_002399_1025

**Comment by astopy** [comment]
@mschwamb That should all be active now.

**Comment by mschwamb** [comment]
Thanks @astopy
