### ISSUE TITLE
Gettings 10 or 20 most favorited images for 2015

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/MarsZoo#154]
Hi, 

I was hoping to putting up a thank you blog post up with the most favorited images from 2015. I don't have access to that info. Is that something that could be provided before the end of the year, and if not past the holidays and new year is fine too. @parrish would this be something you could do or can you recommend who would be the right person?

Thanks, 

~Meg

**Comment by parrish** [comment]
No problem, here are the most favorited.  There are 29, so you can split tied votes however you like.

If you'd like me to regenerate it closer to the end of the year, just send me an email.

[most_favorited.csv.zip](https://github.com/zooniverse/MarsZoo/files/60578/most_favorited.csv.zip)

**Comment by mschwamb** [comment]
Perfect. Thanks @parrish. I wanted to do the same thing for Planet Four: Terrains  as well - that info doesn't seem to be in the panoptes data dumps. Is that something I should ask for on the backend github repo?

**Comment by parrish** [comment]
Here's that data too:

[terrains_most_favorited.csv.zip](https://github.com/zooniverse/MarsZoo/files/61397/terrains_most_favorited.csv.zip)

**Comment by mschwamb** [comment]
Awesome. Thanks very much @parrish and happy holidays!
