### ISSUE TITLE
focusing back on previous target region

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/MarsZoo#155]
Hey @astopy whenever you have a free moment can you pause this subjects. The challenge is mostly over and since the classification rate has dropped significantly it would be good to go back to the smaller target region to try and finish that up first. Can you please pause those subjects that have associated name entry with these HiRISE filenames:

PSP_002399_1025
PSP_002544_1025
PSP_002900_1025
PSP_003322_1025
PSP_002758_0945
PSP_002759_0855
PSP_003179_0945
PSP_003180_0945
PSP_003181_0855
PSP_003363_0945
PSP_003364_0945
PSP_003614_0945
PSP_003680_0945
PSP_003970_0945
PSP_004062_0945
PSP_004181_0945
PSP_004748_0945
PSP_004880_0945
PSP_002567_0955
PSP_002936_0955
PSP_003068_0955
PSP_003213_0955
PSP_003424_0955
PSP_003824_0845
PSP_003912_0955
PSP_004202_0955
PSP_004941_0955
PSP_005046_0955
PSP_003345_0955
PSP_003982_0845

No rush, whenever you're free and have time to do this is fine by us. Many thanks for all the help. Happy Holidays and Happy New Year!

**Comment by astopy** [comment]
Sure, I've paused those again now.
