### ISSUE TITLE
Next set of P4 subjects to unpause

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/MarsZoo#156]
We're close to completing the current set of data live on Planet Four. We'd like the subjects that have associated name entry with these HiRISE filenames below to be unpaused:

PSP_002758_0945
PSP_002759_0855
PSP_003179_0945
PSP_003180_0945
PSP_003181_0855
PSP_003363_0945
PSP_003364_0945
PSP_003614_0945
PSP_003680_0945
PSP_003970_0945
PSP_004062_0945
PSP_004181_0945
PSP_004748_0945
PSP_004880_0945

We do want to finish completely the current data live, so I'll reply to this to ask for this to happen when we need it actually go live if that works for you @astopy .  I wanted to make sure to give a heads up first.  Likely in a few weeks or less depending on the response to the newsletter. Thanks

**Comment by astopy** [comment]
Sure, that’ll be fine. Just let me know.

**Comment by mschwamb** [comment]
Hi @astopy looks likes the newsletter is doing the trick. We're at 99% complete. Before you leave for the day would you be able to switch this on if possible? . If not when we can tomorrow?  Thanks.

**Comment by astopy** [comment]
I won’t get a chance to do it today, but I’ll make a note to do it first thing tomorrow.

**Comment by mschwamb** [comment]
Great. Thanks very much @astopy

**Comment by astopy** [comment]
@mschwamb Those subjects are all active now -- that's 4607 new subjects.

**Comment by mschwamb** [comment]
Thanks @astopy!
