### ISSUE TITLE
Turning off blank images

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/MarsZoo#157]
@astopy when you have a free moment can you pause the following subjects:

APF0001pw2
APF0001pw5
APF0001pw6
APF0001pw7
APF0001pw8
APF0001pwa
APF0001pwc
APF0001pwd
APF0001pwe
APF0001pwh
APF0001pwk
APF0001pwn
APF0001pwp
APF0001pwr
APF0001pwt
APF0001pwu
APF0001px2
APF0001px5
APF0001px9
APF0001pxb
APF0001pxd
APF0001pxg
APF0001pxn
APF0001pxo
APF0001pxq
APF0001pxs
APF0001pxx
APF0001py0
APF0001py2
APF0001py5
APF0001py6
APF0001py7
APF0001py9
APF0001pyc
APF0001pyd
APF0001pye
APF0001pyj
APF0001pyl
APF0001pyn
APF0001pyt
APF0001pyx
APF0001pyz
APF0001pz2
APF0001pz8
APF0001pz9
APF0001pzb
APF0001pzd
APF0001pzk
APF0001pzl
APF0001pzt
APF0001pzu
APF0001pzv
APF0001pzx
APF0001q03
APF0001q04
APF0001q05
APF0001q06
APF0001q07
APF0001q0a
APF0001q0c
APF0001q0d
APF0001q0f
APF0001q0g
APF0001q0h
APF0001q0k
APF0001q0l
APF0001q0q
APF0001q0s
APF0001q0t
APF0001q0u
APF0001q0y
APF0001q0z
APF0001q11
APF0001q13
APF0001q16
APF0001q18
APF0001q1d
APF0001q1g
APF0001q1h
APF0001q1i
APF0001q1k
APF0001q1l
APF0001q1m
APF0001q1o
APF0001q1v
APF0001q1y
APF0001q22
APF0001q23
APF0001q27
APF0001q29

Turns out there was a processing error on the HiRISE image reduction pipeline that added columns of black zero values to one image, so we have about 90 black empty images. I've identified them based their position in the full frame image. So if you can turn these off when you can, that would be great since we don't need these classified. Thanks

**Comment by mschwamb** [comment]
@astopy is this something you can help with? Thanks

**Comment by astopy** [comment]
Oops, sorry I missed this somehow. I’ll take a look this week.

**Comment by astopy** [comment]
These have been paused now.

**Comment by mschwamb** [comment]
Thanks @astopy
