### ISSUE TITLE
Planet Four and login breaks  in Firefox OS X version 45 due to blocking of mixed content

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/MarsZoo#158]
I'm getting 

Blocked loading mixed active content "http://www.planetfour.org/_ouroboros_api/proxy"[Learn More]

in the console. Site comes up without the numbers on the stats on the front page and then you can't log in. Tried clearing my cache but that doesn't seem to help. Chrome and Safari seem fine. 

Other volunteers confirm this as well. See [here](http://talk.planetfour.org/#/boards/BPF0000004/discussions/DPF0000p80?page=1&comment_id=56e85773fc726e5150000275)

**Comment by mschwamb** [comment]
Also impacts Plankton Portal gets the same error in the console and I can't log in on the site. Also their out of data message is playing. 

Galaxy Zoo doesn't have this issue and the other Ouroboros projects I checked.

**Comment by mschwamb** [comment]
Thanks @parrish

**Comment by mschwamb** [comment]
@parrish In case helpful, this is fixed for Planet Four, but Plankton Portal is still having issues for me and it saying it's out of data with log in not working.

**Comment by parrish** [comment]
@mschwamb I don't see an issues right now.  Mind checking again?  We had to update all our old sites, so you may have just tried it before it was fixed.

**Comment by mschwamb** [comment]
Still causing my issues in my version of Firefox. I cleared my cookies and cache. only 20% complete but I get an out of data message and can't log in. 

<img width="535" alt="screen shot 2016-03-17 at 11 37 58 pm" src="https://cloud.githubusercontent.com/assets/753325/13851487/6494de4c-ec99-11e5-845d-16bd26ab1cc9.png">

**Comment by mschwamb** [comment]
Also looks like reports from 6 hours ago on Talk if that's helpful http://talk.planktonportal.org/#/boards/BPK0000002/discussions/DPK0000ej9?page=2&comment_id=56ea7d79325db07420000003 

Planet Four is working fine now. Thanks for fixing that.

**Comment by mschwamb** [comment]
Looks fixed now. I'm able to log in and no error message on PP. Looks like something was updated, and that seemed to sort it.
