### ISSUE TITLE
Getting errors when trying to download the lastest csv dump

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/MarsZoo#159]
@parrish and @astopy the csv data dump from Sunday had errors. I wasn't able to download it. The error was' The specified key does not exist'  I forwarded the full error message with the url link to @parrish.  When you have a moment could someone take a look? Thanks.

**Comment by astopy** [comment]
I guess something went wrong with generating or uploading the file… it was probably just a random network problem or something like that, so it’ll probably work next time it runs.

Unless it’s urgent I’d recommend just waiting until the next one is generated. If you need the data urgently then we can look at manually generating a new one.

**Comment by parrish** [comment]
Yeah, I've been working on getting the data corrected and regenerated.  It takes a while though.  Should hopefully be ready later today.

**Comment by parrish** [comment]
Done now.  The link is in the email I just sent.

**Comment by mschwamb** [comment]
Thanks @parrish . I didn't get an email. I checked my spam folder as well, not sure where it went in the ether. Would you mind sending it again. Thanks!
