### ISSUE TITLE
Pausing live Planet Four subjects other than ESP_046971_0935 

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/MarsZoo#184]
@adammcmaster thanks for getting the new images uploaded. Giving we don't know how long the current website can stay online, can you pause all subjects other than ESP_046971_0935 for the moment? Thanks

**Comment by adammcmaster** [comment]
Sure, I've done that now – but that does only leave 90 subjects active so we should be ready to activate more. Could you let me know which set you'll want after that and I'll keep an eye on things?

**Comment by michaelaye** [comment]
This is our priority order:

```
ESP_046971_0935
ESP_046642_0935
ESP_047103_0935
ESP_047696_0935
ESP_047327_0935
ESP_047459_0935
ESP_046681_0935
ESP_047961_0935
```
Thanks!

**Comment by mschwamb** [comment]
Thanks @adammcmaster. Let's make the first 5 HiRISE images a Michael's list active on Monday, when the newsletter will go out

**Comment by adammcmaster** [comment]
OK, those are active now too.
