### ISSUE TITLE
Can the switch to "Moveable" be more true to the marking?

### ISSUE THREAD

**Issue by michaelaye** [zooniverse/MarsZoo#94]
I often have issues with the mouse-hover switching to "Move-able" state of the marking.
IOW, when I approach a small marking with the mouse, it takes several 'square-pixels' to finally get to the switching point when I can move the marking. Can this be made more truthful to the drawing of the marking?
See my screencast here:
https://dl.dropboxusercontent.com/u/139035/MarsZoo_mouse_test.mov

**Comment by chrissnyder** [comment]
Is this still an issue?
